//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetadataManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetadataManager.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image got a rather poor quality. Are you sure you want to use this?.
        /// </summary>
        internal static string BadPicQualityManagement {
            get {
                return ResourceManager.GetString("BadPicQualityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to {0} files saved..
        /// </summary>
        internal static string ChangesSavedManagement {
            get {
                return ResourceManager.GetString("ChangesSavedManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video converted successfully to audio..
        /// </summary>
        internal static string ConvertedSuccessfullyManagement {
            get {
                return ResourceManager.GetString("ConvertedSuccessfullyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;diverse&quot; is displayed because the selected files have different values..
        /// </summary>
        internal static string DiverseDataManagement1 {
            get {
                return ResourceManager.GetString("DiverseDataManagement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not mean, however, that the data will be saved as &quot;diverse&quot;..
        /// </summary>
        internal static string DiverseDataManagement2 {
            get {
                return ResourceManager.GetString("DiverseDataManagement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File successfully saved to location: {0}.
        /// </summary>
        internal static string FileSavedSuccessfullyManagement {
            get {
                return ResourceManager.GetString("FileSavedSuccessfullyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files successfully deleted..
        /// </summary>
        internal static string FilesDeletedManagement {
            get {
                return ResourceManager.GetString("FilesDeletedManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main folder for managing files:.
        /// </summary>
        internal static string MainFolder {
            get {
                return ResourceManager.GetString("MainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format for metadata:.
        /// </summary>
        internal static string MainFormat {
            get {
                return ResourceManager.GetString("MainFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string MainLanguage {
            get {
                return ResourceManager.GetString("MainLanguage", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing files.
        /// </summary>
        internal static string ManagePageTitle {
            get {
                return ResourceManager.GetString("ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album artist.
        /// </summary>
        internal static string ManagingAlbumArtist {
            get {
                return ResourceManager.GetString("ManagingAlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by album.
        /// </summary>
        internal static string ManagingAlbumGroup {
            get {
                return ResourceManager.GetString("ManagingAlbumGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string ManagingArtist {
            get {
                return ResourceManager.GetString("ManagingArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by album artist.
        /// </summary>
        internal static string ManagingArtistGroup {
            get {
                return ResourceManager.GetString("ManagingArtistGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD number.
        /// </summary>
        internal static string ManagingCDNumber {
            get {
                return ResourceManager.GetString("ManagingCDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to MP3 File.
        /// </summary>
        internal static string ManagingConvertToMp3 {
            get {
                return ResourceManager.GetString("ManagingConvertToMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ManagingDelete {
            get {
                return ResourceManager.GetString("ManagingDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        internal static string ManagingEmptySelection {
            get {
                return ResourceManager.GetString("ManagingEmptySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string ManagingFileName {
            get {
                return ResourceManager.GetString("ManagingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload files.
        /// </summary>
        internal static string ManagingReload {
            get {
                return ResourceManager.GetString("ManagingReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ManagingSave {
            get {
                return ResourceManager.GetString("ManagingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ManagingTitle {
            get {
                return ResourceManager.GetString("ManagingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title number.
        /// </summary>
        internal static string ManagingTitleNumber {
            get {
                return ResourceManager.GetString("ManagingTitleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ManagingYear {
            get {
                return ResourceManager.GetString("ManagingYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} files?.
        /// </summary>
        internal static string UnwantedFilesManagement {
            get {
                return ResourceManager.GetString("UnwantedFilesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to SettingsPageTitle.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
              return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
  }
}
